# Docker Compose file for PostgreSQL
services:
  db:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: backend/user-service
      dockerfile: user-service/Dockerfile
    container_name: user_service
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgresdb

  api-gateway:
    build: backend/api-gateway
    ports:
      - "8081:8081"
    depends_on:
      - user-service
      - product-service
      - order-service

  front:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api-gateway

volumes:
  postgres_data: